image: gradle:8.6-jdk21-alpine

stages:
  - build

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

build:
  stage: build
  timeout: 1h 30m # 타임아웃을 1시간 30분으로 설정
  script:
    - gradle javadoc
  artifacts:
    paths:
      - build/docs/javadoc
    expire_in: 1 week

  only:
    - main